---
# Commented out since SF variables are hardcoded into settings.php
#  - name: Clear Salesforce Variables
#    command:
#    with_items:
#     - mariadb-server
#    register: mariadbinstalled

  - name: Creating /home/vagrant/.drush
    file: path=/home/vagrant/.drush/ state=directory owner=vagrant group=vagrant
    register: drushdir_exists

  - name: Creating tmp dir
    file: path=/var/www/public_html/sites/default/tmp state=directory
    register: tmp

  - name: Drupal -- Copying Drush Alias
    copy: src=drush_alias dest=/home/vagrant/.drush/aliases.drushrc.php owner=vagrant group=vagrant
    when: drushdir_exists|success

  - name: Drupal -- Copying /etc/hosts
    copy: src=hosts dest=/etc/hosts

  - name: Drupal -- Copying settings.php
    copy: src=settings.php dest=/var/www/public_html/sites/default/settings.php

  - name: Drupal Drush -- copying drush install
    copy: src=drush_install.sh dest=/usr/local/bin owner=root group=root mode=0777

  - name: Install Drush
    command: /usr/local/bin/drush_install.sh
    become: true
    become_user: root
