Vagrant.configure(2) do |config|
  config.vm.box = "phase2/centos-7"
  host = RbConfig::CONFIG['host_os']
  # Give VM 1/4 system memory & access to all cpu cores on the host
  if host =~ /darwin/
    cpus = `sysctl -n hw.ncpu`.to_i
    # sysctl returns Bytes and we need to convert to MB
    mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
  elsif host =~ /linux/
    cpus = `nproc`.to_i
    # meminfo shows KB and we need to convert to MB
    mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
  else # sorry Windows folks, I can't help you
    cpus = 2
    mem = 1024
  end
config.vm.provider "virtualbox" do |vb|
  vb.customize ["modifyvm", :id, "--memory", mem]
  vb.customize ["modifyvm", :id, "--cpus", cpus]
  end
  config.vm.network :private_network, ip: "10.220.220.10"
  config.vm.network :forwarded_port, guest: 80, host: 8881
  config.vm.network :forwarded_port, guest: 443, host: 8443
  config.vm.synced_folder "public_html","/var/www/public_html",create:true
  config.vm.synced_folder "db/","/tmp/db",create:true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  config.ssh.insert_key = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      type: :nfs,
      # The nolock option can be useful for an NFSv3 client that wants to avoid the
      # NLM sideband protocol. Without this option, apt-get might hang if it tries
      # to lock files needed for /var/cache/* operations. All of this can be avoided
      # by using NFSv4 everywhere. Please note that the tcp option is not the default.
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
end
